// Random restaurant data that is added to Firestore
// After you've signed into Friendly Eats, click the dropdown
// menu in the top right corner and select "Add random data"

export const randomData = {
  moduleNames: [
    "Caves & Chimaeras",
    "Spellstorm",
    "The Dwarves of Mount Wyrm",
    "Lair of the Necromancer",
    "Siege of Goblin Tower",
    "The Barbarian Raid",
    "Phantasmagorium Ex",
    "Seance at Sunrise",
    "Chateau Rouge",
    "Blood in the Moonlight",
    "Shadows of the Candelabra",
    "Mister Mausoleum",
    "Rope, Cloak, and Scream",
    "Never Stop Running",
    "A Knife in the Night",
    "The Shape",
    "Sunk to the Hilt",
    "Buzzsaw Ballet",
    "Hot Lead Lights My Cigarette",
    "Dirt Poor and Dog Tired",
    "A Slug Too Far",
    "Bloated, Bruised, and Bloodshot",
    "Killer Curves, Steel Nerves",
    "When It Rains, It Pours",
    "Draw Quick And True",
    "You Ask, My Gun Answers",
    "This Train Won't Rob Itself",
    "Coffins and Coffee",
    "Reload!",
    "No Peace At Noon",
    "Redshift",
    "Incident at Ganymede Station",
    "Surface Gravity",
    "Android Hunter",
    "Temporal Displacement",
    "Countdown to Warp",
    "On Assignment",
    "Treasure of the Mummy's Tomb",
    "X Marks the Spot",
    "Dirigible Race",
    "Digging For Clues",
    "Pirates of Spider Bay",
    "Yes, And...",
    "This Pun's For You",
    "Rickets the Clown",
    "Open Mic",
    "Harold",
    "Punch Up",
    "Hero Can't Die",
    "Unlimited Bullets",
    "Innocent Bystander",
    "Slow Motion Explosion",
    "We Can Kill It If It Bleeds",
    "Brawn Not Brains",
    "Fluttering Hearts",
    "Swaying Hips Supple Lips",
    "Rugged Wrangler",
    "Dracula Gets Me Wet",
    "Thorns of the Black Rose",
    "Last Call, Kiss Me Before The Bar Closes"
  ],
  modulePlayers: [
    "One",
    "Two",
    "Three",
    "Four",
    "Five",
    "Six",
    "Seven",
    "Eight"
  ],
  moduleGenres: [
    "Action",
    "Adventure",
    "Comedy",
    "Fantasy",
    "Noir",
    "Horror",
    "Romance",
    "Scifi",
    "Western"
  ],
  moduleReviews: [
    { text: "The food was exceptional, absolutely loved it!", rating: 5 },
    { text: "Delicious dishes and excellent service!", rating: 5 },
    { text: "The flavors were so rich and satisfying.", rating: 5 },
    { text: "Great ambiance and friendly staff.", rating: 5 },
    { text: "A delightful culinary experience!", rating: 5 },
    {
      text: "Mouthwatering dishes that left me wanting more.",
      rating: 5,
    },
    { text: "Perfectly cooked and seasoned meals.", rating: 5 },
    { text: "Incredible presentation and top-notch taste.", rating: 5 },
    { text: "Good food and cozy atmosphere.", rating: 4 },
    { text: "Enjoyed the meal, would come back again.", rating: 4 },
    { text: "Tasty options and reasonable prices.", rating: 4 },
    { text: "Friendly staff, but the food was just okay.", rating: 3 },
    { text: "Decent experience, but nothing extraordinary.", rating: 3 },
    { text: "The food was average, could be better.", rating: 3 },
    {
      text: "Service was slow, and the dishes were disappointing.",
      rating: 2,
    },
    { text: "Expected more, but left unsatisfied.", rating: 2 },
    { text: "Underwhelming taste and presentation.", rating: 2 },
    { text: "Disappointing experience overall.", rating: 2 },
    {
      text: "The food was terrible, will never go back again.",
      rating: 1,
    },
    {
      text: "Worst restaurant experience I've had so far.",
      rating: 1,
    },
    { text: "Avoid this place, the food was inedible.", rating: 1 },
    { text: "Unpleasant service and tasteless dishes.", rating: 1 },
    { text: "Simply outstanding! A culinary masterpiece.", rating: 5 },
    { text: "Couldn't get enough of the amazing flavors.", rating: 5 },
    { text: "Top-notch quality, worth every penny.", rating: 5 },
    { text: "Highly recommended for food enthusiasts.", rating: 5 },
    { text: "Exquisite dishes that pleased my taste buds.", rating: 5 },
    { text: "A gem of a place, impeccable in every aspect.", rating: 5 },
    { text: "Excellent selection of dishes on the menu.", rating: 5 },
    { text: "A fantastic dining experience overall.", rating: 5 },
    {
      text: "The atmosphere was lovely, perfect for a date night.",
      rating: 4,
    },
    { text: "Good food, but the service could be improved.", rating: 4 },
    {
      text: "Pleasantly surprised by the variety of flavors.",
      rating: 4,
    },
    { text: "Well-prepared dishes and friendly staff.", rating: 4 },
    { text: "Satisfying meals, suitable for a quick bite.", rating: 4 },
    { text: "The food was okay, nothing special.", rating: 3 },
    {
      text: "Service could be better, but the taste was fine.",
      rating: 3,
    },
    {
      text: "An average experience, didn't leave a lasting impression.",
      rating: 3,
    },
    { text: "Expected more value for the price.", rating: 2 },
    { text: "Mediocre taste and lackluster presentation.", rating: 2 },
    {
      text: "Regret spending money on such a disappointing meal.",
      rating: 2,
    },
    { text: "Not up to par with my expectations.", rating: 2 },
  ],
};
